# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieFinder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireImage'
    pod 'SwiftyJSON', '~> 4.0'

  # Pods for MovieFinder

end
